### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by evancasey** [bryab/tba-types#3]
Hey Bryan,

Thanks for this awesome project! I'd love to use this for a project I'm working on but I didn't see any examples of how to use with TBA. Any chance you could upload an example script showing how this can be used in TBA?

**Comment by bryab** [comment]
Just want to make sure by TBA you're talking about Toon Boom Harmony?

**Comment by evancasey** [comment]
Yep Toon Boom Harmony is what I meant!

**Comment by bryab** [comment]
Take a look at the main README.md, it describes how to setup `gulp` to compile your scripts in a way that is friendly with Harmony.  You should then be able to put the compiled `.js` files in your scripts folder, and they should show up in Harmony.  Let me know if you have any trouble.  You only need gulp in order to strip out a few things that Harmony doesn't understand, that Typescript generates.

**Comment by bryab** [comment]
I have added some more information to the README.md, and I made an example project here: npm install https://github.com/bryab/tba-types.git

**Comment by evancasey** [comment]
Thanks Bryan!! I will give this a go
